# Update the "app" name with your Fly.io application slug before deploying.
app = "artifactmaker"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

  # --- Sleep when idle; wake on next request ---
  auto_stop_machines = "stop"   # stop/suspend machines when there's no traffic
  auto_start_machines = true    # cold-start on incoming traffic
  min_machines_running = 0      # allow scaling down to zero

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    timeout = "10s"
    path = "/_stcore/health"

[[vm]]
  size = "shared-cpu-1x"

[[mounts]]
  source = "class_data"
  destination = "/app/data"
