# Update the "app" name with your Fly.io application slug before deploying.
app = "class-recorder-placeholder"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    timeout = "10s"
    path = "/_stcore/health"

[[vm]]
  size = "shared-cpu-1x"

[[mounts]]
  source = "class_data"
  destination = "/app/data"
