# Update the "app" name with your Fly.io application slug before deploying.
app = "class-recorder-placeholder"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 20

[[mounts]]
  source = "class_data"
  destination = "/app/data"
